### PR TITLE
[feature]: Add images to the game

### PR DESCRIPTION
**Pull request by Rafajrg21**
## What does this PR do?

This PR makes it so instead of just letters, it shows 16 cards from a collection of  images, some styling was modified as well to have a better presentation of such images. This new functionality can be extended by creating different themes for the game, adding replay value.

The images are smash bros related, because it was the first thing I thought of. 

## Related PRs and Issues

This solves issue #75 

### Screenshots of changes made to the webapp.

A new game looks like this

Already in the game

### Have you updated the README.md file?

- [ ] yes
- [x] no

### Have you made any big breakthrough change?

- [ ] yes
- [x] no

### Is the code beautified?

- [x] yes
- [ ] no

### Is the code clear to understand with proper variable naming and comments?

- [x] yes
- [ ] no

### CODE REVIEW

**Comment by Aatmaj-Zephyr** [comment]
Thanks for the work!
Please fill the pull request template with appropriate checklist and screenshots so I can approve and merge it

**Comment by Rafajrg21** [comment]
@Aatmaj-Zephyr are those screenshots enough? Should I add anything else?

**Comment by Aatmaj-Zephyr** [comment]
Thanks

**Review by Aatmaj-Zephyr — COMMENTED** [review]
Approved after merging

**Pull request merged**
